
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
  - run:
      name: Install PIP
      command: sudo apt-get install python-pip python-dev
  - run:
      name: Install awscli
      command: sudo pip install awscli  
    steps:
      - node/install
      - checkout 
      - aws-cli/setup
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: API Build
          command: |
            npm run api:build      
      - run:
          name: Deploy App
          command: |
            npm run api:deploy 













