
version: 2.1
orbs:
  node: circleci/node@4.1.0
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - python/install-packages:
          pkg-manager: pip 
      - aws-cli/setup
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: API Build
          command: |
            npm run api:build      
      - run:
          name: Deploy App
          command: |
            npm run api:deploy 













