
version: 2.1
orbs:
  node: circleci/node@4.1.0
  python: circleci/python@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  angular: okode/angular@2.0.13
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
       dependencies:
         pre:
      - npm install angular-cli@latest -g
      # - run:
      #     name: Install API Dependencies
      #     command: |
      #       npm run api:install
      # - run:
      #     name: API Build
      #     command: |
      #       npm run api:build      
      # - run:
      #     name: Deploy App
      #     command: |
      #       npm run api:deploy





      - run:
          name: Install Front end Dependencies
          command: |
            npm run api:install
      - run:
          name: Install Front end build
          command: |
            npm run frontend:build 
      - run:
          name: Install Front end Dependencies
          command: |
            npm run frontend:build                 



            
      












