
version: 2.1
orbs:
  # node: circleci/node@4.1.0
  python: circleci/python@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

 
jobs:
    docker:
      # - image: "cimg/base:stable"
      - image: cimg/node:12.16
    steps:
      # - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run: node --version
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: API Build
          command: |
            npm run api:build      
      - run:
          name: Deploy App
          command: |
            npm run api:deploy   
      
      - run:
          name: Install Front end Dependencies
          command: |
            npm run frontend:install
      - run:
          name:  Front end build
          command: |
            npm run frontend:build 
      - run:
          name: Deploy Front end Dependencies
          command: |
            npm run frontend:deploy
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main          
             
                              



            
      












